### ISSUE TITLE
使用自己数据集时报错

### ISSUE THREAD

**Issue by Comedian1926** [xiaoyufenfei/LEDNet#13]
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1550780889552/work/aten/src/THCUNN/generic/SpatialClassNLLCriterion.cu line=128 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "main.py", line 518, in <module>
    main(parser.parse_args())
  File "main.py", line 472, in main
    model = train(args, model, True) #Train encoder
  File "main.py", line 236, in train
    loss = criterion(outputs, targets[:, 0])
  File "/home/disk/software/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/disk/LEDNet/utils/loss.py", line 15, in forward
    return self.loss(F.log_softmax(outputs, dim=0), targets)
  File "/home/disk/software/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/disk/software/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 210, in forward
    return F.nll_loss(input, target, weight=self.weight, ignore_index=self.ignore_index, reduction=self.reduction)
  File "/home/disksoftware/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/functional.py", line 1792, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1550780889552/work/aten/src/THCUNN/generic/SpatialClassNLLCriterion.cu:128

你好，我在使用自己数据集进行训练的时候报了如下错误，数据集格式按照cityscapes文件制作的，图片大小一致、格式一致。修改了类别数目。但是会报如下错误，如果有时间方便看一下吗，十分感谢。。。

**Comment by xiaoyufenfei** [comment]
Please check the data pre-processing yourself, sorry, I can't help.

**Comment by noobliang** [comment]
> THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1550780889552/work/aten/src/THCUNN/generic/SpatialClassNLLCriterion.cu line=128 error=59 : device-side assert triggered
> Traceback (most recent call last):
> File "main.py", line 518, in 
> main(parser.parse_args())
> File "main.py", line 472, in main
> model = train(args, model, True) #Train encoder
> File "main.py", line 236, in train
> loss = criterion(outputs, targets[:, 0])
> File "/home/disk/software/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/disk/LEDNet/utils/loss.py", line 15, in forward
> return self.loss(F.log_softmax(outputs, dim=0), targets)
> File "/home/disk/software/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/disk/software/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 210, in forward
> return F.nll_loss(input, target, weight=self.weight, ignore_index=self.ignore_index, reduction=self.reduction)
> File "/home/disksoftware/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/functional.py", line 1792, in nll_loss
> ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
> RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1550780889552/work/aten/src/THCUNN/generic/SpatialClassNLLCriterion.cu:128
> 
> 你好，我在使用自己数据集进行训练的时候报了如下错误，数据集格式按照cityscapes文件制作的，图片大小一致、格式一致。修改了类别数目。但是会报如下错误，如果有时间方便看一下吗，十分感谢。。。

你好 ，请问一下，自己制作数据集，必须要精细标签gt_fine和弱标签gt_coarse标签吗，大佬，教教我，最近要做一个项目。
