### ISSUE TITLE
histogram calculate

### ISSUE THREAD

**Issue by guaiwuguba** [xiaoyufenfei/LEDNet#16]
What way can I use to calculate the histogram of image classes of my own datasets to get the weights in the train/main.py?

**Comment by xiaoyufenfei** [comment]
def compute_class_weights(self, histogram):
        """to compute the class weights
        Args:
            histogram: distribution of class samples
        """
        normHist = histogram / np.sum(histogram)
        for i in range(self.classes):
            self.classWeights[i] = 1 / (np.log(self.normVal + normHist[i]))

**Comment by xiaoyufenfei** [comment]
·```python
    def compute_class_weights(self, histogram):
        """to compute the class weights
        Args:
            histogram: distribution of class samples
        """
        normHist = histogram / np.sum(histogram)
        for i in range(self.classes):
            self.classWeights[i] = 1 / (np.log(self.normVal + normHist[i]))
```

**Comment by xiaoyufenfei** [comment]
```python
    def compute_class_weights(self, histogram):
        """to compute the class weights
        Args:
            histogram: distribution of class samples
        """
        normHist = histogram / np.sum(histogram)
        for i in range(self.classes):
            self.classWeights[i] = 1 / (np.log(self.normVal + normHist[i]))
```
