### ISSUE TITLE
作者你好 我在训练过程中遇到了如下问题 请解答谢谢你

### ISSUE THREAD

**Issue by anqin5211314** [xiaoyufenfei/LEDNet#23]
for step, (images, labels) in enumerate(loader):
            print('images = ',images.shape)  #images =  torch.Size([5, 3, 512, 682])
            print('labels = ',labels.shape)  #labels =  torch.Size([5, 1, 64, 85])
            inputs = images.cuda()
            targets = labels.cuda()
           
            start_time = time.time()

            #print('inputs= ',inputs.shape)   # inputs=  torch.Size([5, 3, 512, 682])
            #print('targets= ',targets.shape) # targets=  torch.Size([5, 1, 64, 85])

            imgs_batch = images.shape[0]
            if imgs_batch != args.batch_size:
                break            
                                     
            outputs = model(inputs, only_encode=enc)
            print('outputs = ',outputs)
            print('outputs=',outputs.shape) #torch.Size([5, 2, 64, 86])
            print('targets[:, 0] = ',targets[:, 0].shape) #torch.Size([5, 64, 85])
input经过model()后输出的output的size变成了([5, 2, 64, 86]) 与标签维度不符合 出现了错误  请问什么原因可以造成这样的结果呢？

**Comment by xiaoyufenfei** [comment]
Sorry, my training image size is 512x1024, the tensor dimension doesn't match problem, which is caused by the deconvolution operation, is easy to check by printing each tensor dimension, it is easy to change right for you training process.

**Comment by noobliang** [comment]
> for step, (images, labels) in enumerate(loader):
> print('images = ',images.shape) #images = torch.Size([5, 3, 512, 682])
> print('labels = ',labels.shape) #labels = torch.Size([5, 1, 64, 85])
> inputs = images.cuda()
> targets = labels.cuda()
> 
> ```
>         start_time = time.time()
> 
>         #print('inputs= ',inputs.shape)   # inputs=  torch.Size([5, 3, 512, 682])
>         #print('targets= ',targets.shape) # targets=  torch.Size([5, 1, 64, 85])
> 
>         imgs_batch = images.shape[0]
>         if imgs_batch != args.batch_size:
>             break            
>                                  
>         outputs = model(inputs, only_encode=enc)
>         print('outputs = ',outputs)
>         print('outputs=',outputs.shape) #torch.Size([5, 2, 64, 86])
>         print('targets[:, 0] = ',targets[:, 0].shape) #torch.Size([5, 64, 85])
> ```
> 
> input经过model()后输出的output的size变成了([5, 2, 64, 86]) 与标签维度不符合 出现了错误 请问什么原因可以造成这样的结果呢？

你好，请问能分享下预训练权重吗，作者给的链接失效了， 发邮箱(99249635qq@.com)或者百度云盘都可以，非常感谢。
