### ISSUE TITLE
训练时出现问题

### ISSUE THREAD

**Issue by Liu6697** [xiaoyufenfei/LEDNet#27]
你好，当我运行python main.py --savedir logs --model lednet --datadir D:/bishe/LEDNet-master/datasets/cityscapes时，跳出错误

========== ENCODER TRAINING ===========
D:/bishe/LEDNet-master/datasets/cityscapes\leftImg8bit/train
D:/bishe/LEDNet-master/datasets/cityscapes\leftImg8bit/val
<class 'utils.loss.CrossEntropyLoss2d'>
----- TRAINING - EPOCH 1 -----
LEARNING RATE:  0.0005
Traceback (most recent call last):
  File "main.py", line 510, in <module>
    main(parser.parse_args())
  File "main.py", line 464, in main
    model = train(args, model, True) #Train encoder
  File "main.py", line 211, in train
    for step, (images, labels) in enumerate(loader):
  File "C:\Users\admin\anaconda3\envs\DFANet\lib\site-packages\torch\utils\data\dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "C:\Users\admin\anaconda3\envs\DFANet\lib\site-packages\torch\utils\data\dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\envs\DFANet\lib\site-packages\torch\utils\data\dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\Users\admin\anaconda3\envs\DFANet\lib\site-packages\torch\utils\data\dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\bishe\LEDNet-master\utils\dataset.py", line 86, in __getitem__
    filenameGt = self.filenamesGt[index]
IndexError: list index out of range

请问这个问题应该怎么解决

**Comment by ABDULMAWLA** [comment]
Hello Liu6697
Did you solve this problem

**Comment by Liu6697** [comment]
Yes, @ABDULMAWLA  
please download [CityscapesScripts](https://github.com/mcordts/cityscapesScripts), and convert the dataset to [19 categories](https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/helpers/labels.py). The dataset should have this basic structure.

**Comment by Benjiaminh** [comment]
我遇到过，没记错的话应该要去改dataset.py

**Comment by Benjiaminh** [comment]
> 你好，当我运行python main.py --savedir logs --model lednet --datadir D:/bishe/LEDNet-master/datasets/cityscapes时，跳出错误
> 
> ========== ENCODER TRAINING ===========
> D:/bishe/LEDNet-master/datasets/cityscapes\leftImg8bit/train
> D:/bishe/LEDNet-master/datasets/cityscapes\leftImg8bit/val
> <class 'utils.loss.CrossEntropyLoss2d'>
> ----- TRAINING - EPOCH 1 -----
> LEARNING RATE: 0.0005
> Traceback (most recent call last):
> File "main.py", line 510, in
> main(parser.parse_args())
> File "main.py", line 464, in main
> model = train(args, model, True) #Train encoder
> File "main.py", line 211, in train
> for step, (images, labels) in enumerate(loader):
> File "C:\Users\admin\anaconda3\envs\DFANet\lib\site-packages\torch\utils\data\dataloader.py", line 336, in **next**
> return self._process_next_batch(batch)
> File "C:\Users\admin\anaconda3\envs\DFANet\lib\site-packages\torch\utils\data\dataloader.py", line 357, in _process_next_batch
> raise batch.exc_type(batch.exc_msg)
> IndexError: Traceback (most recent call last):
> File "C:\Users\admin\anaconda3\envs\DFANet\lib\site-packages\torch\utils\data\dataloader.py", line 106, in _worker_loop
> samples = collate_fn([dataset[i] for i in batch_indices])
> File "C:\Users\admin\anaconda3\envs\DFANet\lib\site-packages\torch\utils\data\dataloader.py", line 106, in
> samples = collate_fn([dataset[i] for i in batch_indices])
> File "D:\bishe\LEDNet-master\utils\dataset.py", line 86, in **getitem**
> filenameGt = self.filenamesGt[index]
> IndexError: list index out of range
> 
> 请问这个问题

> 你好，当我运行python main.py --savedir logs --model lednet --datadir D:/bishe/LEDNet-master/datasets/cityscapes时，跳出错误
> 
> ========== ENCODER TRAINING ===========
> D:/bishe/LEDNet-master/datasets/cityscapes\leftImg8bit/train
> D:/bishe/LEDNet-master/datasets/cityscapes\leftImg8bit/val
> <class 'utils.loss.CrossEntropyLoss2d'>
> ----- TRAINING - EPOCH 1 -----
> LEARNING RATE: 0.0005
> Traceback (most recent call last):
> File "main.py", line 510, in
> main(parser.parse_args())
> File "main.py", line 464, in main
> model = train(args, model, True) #Train encoder
> File "main.py", line 211, in train
> for step, (images, labels) in enumerate(loader):
> File "C:\Users\admin\anaconda3\envs\DFANet\lib\site-packages\torch\utils\data\dataloader.py", line 336, in **next**
> return self._process_next_batch(batch)
> File "C:\Users\admin\anaconda3\envs\DFANet\lib\site-packages\torch\utils\data\dataloader.py", line 357, in _process_next_batch
> raise batch.exc_type(batch.exc_msg)
> IndexError: Traceback (most recent call last):
> File "C:\Users\admin\anaconda3\envs\DFANet\lib\site-packages\torch\utils\data\dataloader.py", line 106, in _worker_loop
> samples = collate_fn([dataset[i] for i in batch_indices])
> File "C:\Users\admin\anaconda3\envs\DFANet\lib\site-packages\torch\utils\data\dataloader.py", line 106, in
> samples = collate_fn([dataset[i] for i in batch_indices])
> File "D:\bishe\LEDNet-master\utils\dataset.py", line 86, in **getitem**
> filenameGt = self.filenamesGt[index]
> IndexError: list index out of range
> 
> 请问这个问题应该怎么解决

这个我知道怎么改，但是我改了之后报了其他错，你关闭了这个问题，是你解决了这个问题吗，你有遇到其他问题吗
